### ISSUE TITLE
Use debug log level instead of verbose flag

### ISSUE THREAD

**Issue by szkiba** [grafana/k6foundry#18]
In a library code, I consider the use of standard log levels (e.g. debug level) to be a better practice than the use of the verbose flag.

https://github.com/grafana/k6foundry/blob/a668c34830f1d1dc3e083bf83cccf06e24e1f574/native.go#L57

**Comment by pablochacin** [comment]
Verbose flag has a different meaning than log level. Verbose means the actual output of the go commands is sent to output. I think both make sense.

**Comment by szkiba** [comment]
In k6 v1 run experience development, I think the logging logic used in k6 should be followed. In k6, the verbose flag turns on debug level logging and does not add extra info level log entries.

**Comment by pablochacin** [comment]
Conventions and guidelines are good to follow but not at the expense of losing functionality.
Having detailed output from `go` commands is useful, mostly when debugging.
Also, `k6foundry` is more related to the k6 build service than k6 itself, so we need to consider the specific requirements here.

**Comment by szkiba** [comment]
I don't really understand, if it's "mostly when debugging" then why isn't it a debug log level?

In my opinion, the logging of the build service differs only in that you have to be able to solve the log level setting at the per request level. A possible solution for this (I used this in the past) is to use the W3C "Trace Context", which will have to be supported anyway due to tracing.

But this is the competence of the team operating and developing the build service, it is not necessary to figure it out now. What we can do at the moment is to use the context-dependent logger.

**Comment by pablochacin** [comment]
> Also, k6foundry is more related to the k6 build service than k6 itself, so we need to consider the specific requirements here.
I mean here that the foundry is expected to be used by `xk6` that has nothing to do with the build service

**Comment by szkiba** [comment]
> Because we are capturing all the output from the go commands and sending to stdout/stderr. 

This is an interesting problem. I would not expect a library to write anything as a log to the stdout/stderr peripherals.

In the standard go log package, the Writer can be requested from the Logger. I use this in such cases. Of course, it requires a little preparation, because if there is another logger in the project, then you need an adapter to the standard logger.

I'm not saying that this is a cardinal issue, but I would expect that a low-level library does not write to stdout/stderr peripherals.

**Comment by pablochacin** [comment]
> This is an interesting problem.
Yes. 

>  I would not expect a library to write anything as a log to the stdout/stderr peripherals.

The library receives the writers for stderr and stdout. It should be the CLI that passes the stdout/stderr devices. 

However, I checked the code and now the library is setting them if none is defined. I will change this so the library never sets these writers. 
```
	if opts.Verbose {
		logLevel = logrus.InfoLevel

		if opts.Stdout == nil {
			opts.Stdout = os.Stdout
		}

		if opts.Stderr == nil {
			opts.Stderr = os.Stderr
		}
	}
```

**Comment by szkiba** [comment]
All right. If I understand correctly, if it receives an `opts.Stdout/opts.Stderr` value, it writes there, if it doesn't, it doesn't write anywhere. I think that's fine. Then the Verbose parameter is not needed...
