### ISSUE TITLE
Default to statically linked binary

### ISSUE THREAD

**Issue by szkiba** [grafana/k6foundry#38]
The native builder (`{GoOpts: {CopyGoEnv:true}}`) creates a dynamically linked binary on Linux as if cgo is enabled by default.

It would be a better user experience if it worked like the go toolkit, i.e. a statically linked binary would be created by default.

**Comment by pablochacin** [comment]
>It would be a better user experience if it worked like the go toolkit, i.e. a statically linked binary would be created by default.

@szkiba not sure what you mean here. Could you elaborate?

 `CopyGoEnv:true` copies the current go env, which includes the CGO_ENABLED.
That is, it does not override the go tool kit's default.
